# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='name', max_length=300, verbose_name='Recipe Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(verbose_name='Recipe Instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servingsize',
            field=models.IntegerField(verbose_name='Serving Size'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.URLField(blank=True, verbose_name='Recipe Source URL'),
        ),
    ]
